targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/infrastructure/graphql/**
          clients:
            - graphql
            - graphql_flutter
